package certprofile

import (
	"bytes"
	"crypto/rand"
	"crypto/sha256"
	"crypto/x509"
	"encoding/base64"
	"encoding/pem"
	"encoding/xml"
	"errors"
	"fmt"
	"html"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"
)

type MissingInstallerError struct {
	ProfilePath string
}

func (e MissingInstallerError) Error() string {
	return "no supported iOS profile installer found in PATH"
}

type InstallerRunError struct {
	Display string
	Err     error
	Output  string
}

func (e InstallerRunError) Error() string {
	return fmt.Sprintf("%s failed: %v", e.Display, e.Err)
}

type Options struct {
	CertPath string
	OutPath  string
	Name     string
	Install  bool
}

type VerifyReport struct {
	Fingerprint    string
	Subject        string
	Expires        string
	ProfilePath    string
	ProfileChecked bool
	ProfileMatches bool
}

func Verify(certPath, profilePath string) (VerifyReport, error) {
	content, err := os.ReadFile(certPath)
	if err != nil {
		return VerifyReport{}, err
	}
	der := certBytes(content)
	certificate, err := x509.ParseCertificate(der)
	if err != nil {
		return VerifyReport{}, fmt.Errorf("parse Burp CA certificate: %w", err)
	}
	digest := sha256.Sum256(der)
	report := VerifyReport{
		Fingerprint: strings.ToUpper(fmt.Sprintf("%x", digest[:])),
		Subject:     certificate.Subject.String(),
		Expires:     certificate.NotAfter.UTC().Format(time.RFC3339),
	}
	if strings.TrimSpace(profilePath) == "" {
		return report, nil
	}
	profile, err := os.ReadFile(profilePath)
	if err != nil {
		return VerifyReport{}, err
	}
	report.ProfilePath = profilePath
	report.ProfileChecked = true
	report.ProfileMatches = profileContainsCertificate(profile, der)
	return report, nil
}

func profileContainsCertificate(profile, der []byte) bool {
	decoder := xml.NewDecoder(bytes.NewReader(profile))
	for {
		token, err := decoder.Token()
		if err != nil {
			return false
		}
		start, ok := token.(xml.StartElement)
		if !ok || start.Name.Local != "data" {
			continue
		}
		var encoded string
		if err := decoder.DecodeElement(&encoded, &start); err != nil {
			return false
		}
		decoded, err := base64.StdEncoding.DecodeString(strings.Join(strings.Fields(encoded), ""))
		if err == nil && bytes.Equal(decoded, der) {
			return true
		}
	}
}

func Build(options Options) ([]byte, error) {
	if strings.TrimSpace(options.CertPath) == "" {
		return nil, fmt.Errorf("missing Burp CA certificate path")
	}
	if strings.TrimSpace(options.Name) == "" {
		options.Name = "Burp Suite CA"
	}
	cert, err := os.ReadFile(options.CertPath)
	if err != nil {
		return nil, err
	}
	certDER := certBytes(cert)
	if len(certDER) == 0 {
		return nil, fmt.Errorf("certificate file is empty or invalid")
	}
	payloadUUID, err := uuid()
	if err != nil {
		return nil, err
	}
	profileUUID, err := uuid()
	if err != nil {
		return nil, err
	}
	now := time.Now().UTC().Format("20060102150405")
	return []byte(fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>PayloadContent</key>
  <array>
    <dict>
      <key>PayloadCertificateFileName</key>
      <string>%s.cer</string>
      <key>PayloadContent</key>
      <data>%s</data>
      <key>PayloadDescription</key>
      <string>Installs the Burp Suite CA certificate for authorized iOS traffic interception lab testing.</string>
      <key>PayloadDisplayName</key>
      <string>%s</string>
      <key>PayloadIdentifier</key>
      <string>com.waariss.jailbreakit.burp-ca.%s.cert</string>
      <key>PayloadType</key>
      <string>com.apple.security.root</string>
      <key>PayloadUUID</key>
      <string>%s</string>
      <key>PayloadVersion</key>
      <integer>1</integer>
    </dict>
  </array>
  <key>PayloadDescription</key>
  <string>Burp CA profile generated by jailbreakit for authorized iOS security testing only.</string>
  <key>PayloadDisplayName</key>
  <string>%s</string>
  <key>PayloadIdentifier</key>
  <string>com.waariss.jailbreakit.burp-ca.%s</string>
  <key>PayloadOrganization</key>
  <string>jailbreakit</string>
  <key>PayloadRemovalDisallowed</key>
  <false/>
  <key>PayloadType</key>
  <string>Configuration</string>
  <key>PayloadUUID</key>
  <string>%s</string>
  <key>PayloadVersion</key>
  <integer>1</integer>
</dict>
</plist>
`, html.EscapeString(options.Name), base64.StdEncoding.EncodeToString(certDER), html.EscapeString(options.Name), now, payloadUUID, html.EscapeString(options.Name), now, profileUUID)), nil
}

func Write(options Options) (string, error) {
	profile, err := Build(options)
	if err != nil {
		return "", err
	}
	out := strings.TrimSpace(options.OutPath)
	if out == "" {
		out = "burp-ca.mobileconfig"
	}
	if dir := filepath.Dir(out); dir != "." {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return "", err
		}
	}
	if err := os.WriteFile(out, profile, 0o644); err != nil {
		return "", err
	}
	return out, nil
}

func Install(profilePath string, stdout, stderr io.Writer) error {
	if strings.TrimSpace(profilePath) == "" {
		return fmt.Errorf("missing mobileconfig path")
	}
	command, ok := profileInstaller(profilePath)
	if !ok {
		return MissingInstallerError{ProfilePath: profilePath}
	}
	fmt.Fprintf(stdout, "[*] Installing profile with %s\n", command.display)
	cmd := exec.Command(command.path, command.args...)
	cmd.Stdin = os.Stdin
	var output bytes.Buffer
	cmd.Stdout = &output
	cmd.Stderr = &output
	err := cmd.Run()
	if output.Len() > 0 {
		if err == nil {
			_, _ = stdout.Write(output.Bytes())
		} else {
			fmt.Fprintln(stderr, firstUsefulLine(output.String()))
		}
	}
	if err != nil {
		return InstallerRunError{
			Display: command.display,
			Err:     err,
			Output:  output.String(),
		}
	}
	return nil
}

func IsMissingInstaller(err error) bool {
	var missing MissingInstallerError
	return errors.As(err, &missing)
}

func IsInstallerRunError(err error) bool {
	var runErr InstallerRunError
	return errors.As(err, &runErr)
}

func InstallerHints(w io.Writer, profilePath string) {
	fmt.Fprintln(w, "[!] no supported iOS profile installer found in PATH")
	fmt.Fprintln(w, "[*] Install one of these host tools, then retry:")
	fmt.Fprintln(w, "    macOS/Linux: python3 -m pip install pymobiledevice3")
	fmt.Fprintln(w, "    macOS: install Apple Configurator for cfgutil")
	fmt.Fprintln(w, "    Linux distro package, if available: ideviceprofile")
	fmt.Fprintln(w, "[*] Manual fallback: transfer this file to the iPhone and open it:")
	fmt.Fprintf(w, "    %s\n", profilePath)
}

func InstallerFailureHints(w io.Writer) {
	fmt.Fprintln(w, "[*] Check that the iPhone is connected over USB, unlocked, paired, and trusted.")
	fmt.Fprintln(w, "[*] On Linux, check that usbmuxd is running and your user can access the device.")
	fmt.Fprintln(w, "[*] You can still transfer the generated .mobileconfig to the iPhone and open it manually.")
}

func TrustInstructions(w io.Writer) {
	fmt.Fprintln(w, "[>] iPhone action: install the profile in Settings > General > VPN & Device Management")
	fmt.Fprintln(w, "[>] Enable full trust: Settings > General > About > Certificate Trust Settings")
	fmt.Fprintln(w, "[>] Then enable the toggle for: Burp Suite CA")
	fmt.Fprintln(w, "[!] Did you enable full trust? jailbreakit does not bypass or auto-enable iOS certificate trust.")
}

func certBytes(content []byte) []byte {
	block, _ := pem.Decode(content)
	if block != nil && block.Type == "CERTIFICATE" {
		return block.Bytes
	}
	return content
}

func firstUsefulLine(text string) string {
	lines := strings.Split(text, "\n")
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if isUsefulErrorLine(line) {
			return line
		}
	}
	for _, line := range lines {
		line = strings.TrimSpace(line)
		if line == "" || strings.Contains(line, "Traceback") || strings.HasPrefix(line, "│") || strings.HasPrefix(line, "╭") || strings.HasPrefix(line, "╰") {
			continue
		}
		return line
	}
	return strings.TrimSpace(text)
}

func isUsefulErrorLine(line string) bool {
	if line == "" || strings.Contains(line, "Traceback") {
		return false
	}
	return strings.Contains(line, "Error:") || strings.Contains(line, "error:") || strings.Contains(line, "PermissionError:")
}

type installCommand struct {
	path    string
	args    []string
	display string
}

func profileInstaller(profilePath string) (installCommand, bool) {
	candidates := []struct {
		binary  string
		args    []string
		display string
	}{
		{
			binary:  "ideviceprofile",
			args:    []string{"install", profilePath},
			display: "ideviceprofile",
		},
		{
			binary:  "pymobiledevice3",
			args:    []string{"profile", "install", profilePath},
			display: "pymobiledevice3 profile install",
		},
	}
	if runtimeGOOS() == "darwin" {
		candidates = append(candidates, struct {
			binary  string
			args    []string
			display string
		}{
			binary:  "cfgutil",
			args:    []string{"install-profile", profilePath},
			display: "cfgutil install-profile",
		})
	}
	for _, candidate := range candidates {
		path, err := exec.LookPath(candidate.binary)
		if err == nil {
			return installCommand{
				path:    path,
				args:    candidate.args,
				display: candidate.display,
			}, true
		}
	}
	return installCommand{}, false
}

func uuid() (string, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return "", err
	}
	b[6] = (b[6] & 0x0f) | 0x40
	b[8] = (b[8] & 0x3f) | 0x80
	return fmt.Sprintf("%08x-%04x-%04x-%04x-%012x", b[0:4], b[4:6], b[6:8], b[8:10], b[10:16]), nil
}

var runtimeGOOS = func() string {
	return runtime.GOOS
}
